"""Tests for the markdown hard-wrap check."""

from __future__ import annotations

from pathlib import Path

from tara import markdown_lint


def test_clean_one_sentence_per_line_has_no_violations():
    text = (
        "# Title\n\n"
        "This is one sentence on its own line.\n"
        "This is another sentence on its own line.\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_hard_wrapped_paragraph_is_flagged():
    text = (
        "This document contains the core Python coding standards that apply to\n"
        "80% of the code. These principles are loaded with every skill invocation.\n"
    )
    violations = markdown_lint.find_violations(text)
    assert len(violations) == 1
    assert violations[0].line == 1


def test_long_single_line_paragraph_is_not_flagged():
    text = (
        "This is a very long single sentence that just keeps going and going " * 3
        + "\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_list_items_each_on_own_line_are_not_flagged():
    text = "- First item ends cleanly.\n- Second item ends cleanly too.\n"
    assert markdown_lint.find_violations(text) == []


def test_list_items_without_terminal_punctuation_are_not_flagged_as_wrap():
    text = "* `--ref TEXT`: Branch, tag, or commit SHA\n* `--name TEXT`: Local skill name\n"
    assert markdown_lint.find_violations(text) == []


def test_wrapped_list_item_continuation_is_flagged():
    text = (
        "- First item that keeps going onto the\n  next physical line before it ends.\n"
    )
    violations = markdown_lint.find_violations(text)
    assert len(violations) == 1
    assert violations[0].line == 1


def test_consecutive_bold_label_lines_are_not_flagged():
    text = (
        "**Correctness** — bugs, edge cases, error handling gaps\n"
        "**Clarity** — naming, complexity, readability\n"
        "**Tests** — missing coverage for the changed behaviour\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_consecutive_bold_colon_label_lines_are_not_flagged():
    text = (
        "**Correctness**: bugs, edge cases, error handling gaps\n"
        "**Clarity**: naming, complexity, readability; clear over clever\n"
        "**Tests**: behaviour covered once, tests independent, the gate would pass\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_consecutive_label_colon_lines_are_not_flagged():
    text = (
        "Date: {date}\nSeverity: P{1-4}\nStatus: Draft | Review | Closed\nAuthor(s):\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_fenced_code_block_is_ignored():
    text = (
        "```text\n"
        "some code that is not wrapped properly at all\n"
        "and continues here without any punctuation\n"
        "```\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_table_rows_are_ignored():
    text = "| a | b |\n| - | - |\n| this row has no period | neither does this one |\n"
    assert markdown_lint.find_violations(text) == []


def test_headings_break_the_paragraph_run():
    text = "## A heading with no period\nA sentence right after it.\n"
    assert markdown_lint.find_violations(text) == []


def test_blank_line_separated_paragraphs_are_independent():
    text = "First paragraph, one clause without terminal punctuation\n\nSecond paragraph.\n"
    assert markdown_lint.find_violations(text) == []


def test_frontmatter_block_is_ignored():
    text = (
        "---\n"
        "description: a long description with no terminal punctuation at all\n"
        "tools: [read, search]\n"
        "---\n\n"
        "Body sentence.\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_consecutive_html_comments_are_not_flagged():
    text = (
        "<!-- Generated by scripts/gen_cli_docs.py. Do not edit by hand. -->\n"
        "<!-- Run `uv run python scripts/gen_cli_docs.py` to refresh. -->\n"
    )
    assert markdown_lint.find_violations(text) == []


def test_check_file_reports_path_and_line(tmp_path: Path):
    md = tmp_path / "doc.md"
    md.write_text(
        "This line is wrapped mid sentence and continues\nonto the next line here.\n"
    )
    violations = markdown_lint.check_file(md)
    assert len(violations) == 1
    assert violations[0].path == md
    assert violations[0].line == 1


def test_main_returns_nonzero_and_prints_violations(tmp_path: Path, capsys):
    md = tmp_path / "doc.md"
    md.write_text(
        "This line is wrapped mid sentence and continues\nonto the next line here.\n"
    )
    exit_code = markdown_lint.main([str(md)])
    out = capsys.readouterr().out
    assert exit_code == 1
    assert "doc.md" in out


def test_main_returns_zero_for_clean_files(tmp_path: Path):
    md = tmp_path / "doc.md"
    md.write_text("This is a clean sentence.\n")
    assert markdown_lint.main([str(md)]) == 0
