"""Port a GitHub Copilot setup into Claude Code files.

Copilot's ``.github/`` layout is the single source of truth. This module
projects it into the files Claude Code reads, so there is only ever one copy to
maintain:

- ``CLAUDE.md``            a thin pointer that ``@``-imports
                           ``.github/copilot-instructions.md`` (no duplicated
                           instruction text)
- ``.claude/agents/``      translated from ``.github/agents/*.agent.md``
- ``.claude/commands/``    translated from ``.github/prompts/**/*.prompt.md``
                           plus starter ``check``/``review`` commands
- ``.claude/skills/``      mirrored from ``.github/skills/`` (identical SKILL.md)

MCP needs no translation: Claude Code reads the repo-root ``.mcp.json`` with the
same ``mcpServers`` schema Tara already writes.

Everything here is generated; users edit the Copilot side (or Tara's central
standard) and re-run ``tara tools`` to regenerate.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from pydantic import Field

from tara import frontmatter
from tara.core import (
    CLAUDE_INSTRUCTIONS,
    COPILOT_INSTRUCTIONS,
    MCP_CONFIG,
    repo_root,
)
from tara.frontmatter import Frontmatter

# Copilot sources.
COPILOT_AGENTS_DIR = Path(".github") / "agents"
COPILOT_PROMPTS_DIR = Path(".github") / "prompts"
COPILOT_SKILLS_DIR = Path(".github") / "skills"

# Claude Code destinations.
CLAUDE_AGENTS_DIR = Path(".claude") / "agents"
CLAUDE_COMMANDS_DIR = Path(".claude") / "commands"
CLAUDE_SKILLS_DIR = Path(".claude") / "skills"

# Marks a CLAUDE.md as Tara-generated. A CLAUDE.md without it is hand-written,
# so the port leaves it alone rather than destroying the user's own context.
GENERATED_MARKER = "<!-- generated by `tara tools` -->"

# Copilot's tool vocabulary mapped onto Claude Code's built-in tool names. One
# Copilot capability can imply several Claude tools (``search`` covers both
# Glob and Grep).
_TOOL_MAP: dict[str, tuple[str, ...]] = {
    "read": ("Read",),
    "search": ("Glob", "Grep"),
    "edit": ("Edit", "Write"),
    "write": ("Write",),
    "create": ("Write",),
    "apply_patch": ("Edit",),
    "patch": ("Edit",),
    "execute": ("Bash",),
    "bash": ("Bash",),
    "shell": ("Bash",),
    "terminal": ("Bash",),
    "run": ("Bash",),
    "fetch": ("WebFetch",),
    "websearch": ("WebSearch",),
    "web_search": ("WebSearch",),
}


class ClaudeAgent(Frontmatter):
    """Frontmatter of a Claude Code subagent (``.claude/agents/<name>.md``).

    ``tools`` is an allowlist written as a comma-separated string; leaving it
    unset lets the subagent inherit the full toolset.
    """

    name: str
    description: str | None = None
    tools: str | None = None


class ClaudeCommand(Frontmatter):
    """Frontmatter of a Claude Code slash command (``.claude/commands/<name>.md``).

    ``allowed_tools`` is emitted as ``allowed-tools``, the key Claude Code reads
    to permit the ``!`` bash pre-execution in a command body. The rename is a
    serialization alias, so the field keeps its Python name on construction.
    """

    description: str | None = None
    allowed_tools: str | None = Field(default=None, serialization_alias="allowed-tools")


# Starter commands, written only when the Copilot prompts didn't already
# produce a command of the same name and the file doesn't already exist.
_STARTER_COMMANDS: dict[str, tuple[ClaudeCommand, str]] = {
    "check.md": (
        ClaudeCommand(
            description="Run the lint and test gate (ruff + pytest)",
            allowed_tools="Bash(uv run:*)",
        ),
        "Run the project check gate and report any failures:\n\n"
        "!`uv run ruff check --fix && uv run ruff format && uv run pytest`",
    ),
    "review.md": (
        ClaudeCommand(
            description="Review staged changes for quality and correctness",
            allowed_tools="Bash(git diff:*)",
        ),
        "Use the gilfoyle subagent to review these staged changes for quality,"
        " correctness, and performance issues:\n\n"
        "!`git diff --staged`",
    ),
}


def _write_text(dest: Path, text: str, dry_run: bool) -> str:
    root = repo_root()
    rel = dest.relative_to(root)
    if dry_run:
        return f"  [dry-run] {rel}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text)
    return f"  wrote {rel}"


# ── Frontmatter translation ───────────────────────────────────────────────────


def claude_tools(copilot_tools: object) -> list[str]:
    """Map a Copilot ``tools`` value onto sorted Claude Code tool names.

    Unknown names are dropped: granting a tool Claude does not have would make
    the whole allowlist invalid.
    """
    names: set[str] = set()
    for tool in frontmatter.tokens(copilot_tools):
        names.update(_TOOL_MAP.get(tool, ()))
    return sorted(names)


def claude_agent_name(filename: str) -> str:
    """Map ``foo.agent.md`` (Copilot) to the Claude subagent name ``foo``."""
    return filename.removesuffix(".agent.md")


def translate_agent(source: Path) -> str:
    """Translate a Copilot ``.agent.md`` file into Claude Code subagent markdown."""
    fm, body = frontmatter.parse(source.read_text())
    tools = claude_tools(fm.get("tools"))
    agent = ClaudeAgent(
        name=claude_agent_name(source.name),
        description=frontmatter.text_of(fm.get("description")) or None,
        tools=", ".join(tools) or None,
    )
    return agent.render(body)


def translate_prompt(source: Path) -> str:
    """Translate a Copilot ``.prompt.md`` file into a Claude Code slash command.

    Keeps the ``description`` and body; drops Copilot-only frontmatter
    (``agent``/``tools``) that Claude commands don't use.
    """
    fm, body = frontmatter.parse(source.read_text())
    description = frontmatter.text_of(fm.get("description"))
    if not description:
        return f"{body.strip()}\n"
    return ClaudeCommand(description=description).render(body)


# ── Port steps ────────────────────────────────────────────────────────────────


def port_instructions(dry_run: bool = False) -> str:
    """Write ``CLAUDE.md`` as a pointer importing the Copilot instructions.

    A pre-existing CLAUDE.md that Tara did not generate is left untouched, so a
    hand-written project brief is never clobbered.
    """
    root = repo_root()
    dest = root / CLAUDE_INSTRUCTIONS
    if dest.exists() and GENERATED_MARKER not in dest.read_text():
        return (
            f"  skipped {CLAUDE_INSTRUCTIONS} (hand-written; add "
            f"`@{COPILOT_INSTRUCTIONS.as_posix()}` to it yourself)"
        )
    text = (
        f"{GENERATED_MARKER}\n"
        f"<!-- Edit {COPILOT_INSTRUCTIONS.as_posix()} instead, then re-run "
        f"`tara tools`. -->\n\n"
        f"# Project instructions\n\n"
        f"@{COPILOT_INSTRUCTIONS.as_posix()}\n"
    )
    return _write_text(dest, text, dry_run)


def port_mcp() -> str:
    """Report on ``.mcp.json``; Claude Code reads Tara's schema as-is.

    Nothing is written: Copilot and Claude Code share the repo-root
    ``mcpServers`` format, so the file Tara already wrote is the one Claude
    Code loads.
    """
    rel = MCP_CONFIG.as_posix()
    if (repo_root() / MCP_CONFIG).exists():
        return f"  reused {rel} (Claude Code reads it natively, no port needed)"
    return f"  missing {rel} (run `tara init` to write it)"


def port_agents(dry_run: bool = False) -> list[str]:
    """Translate every ``.github/agents/*.agent.md`` into ``.claude/agents/``."""
    root = repo_root()
    src_dir = root / COPILOT_AGENTS_DIR
    if not src_dir.is_dir():
        return []
    lines: list[str] = []
    for src in sorted(src_dir.glob("*.agent.md")):
        dest = root / CLAUDE_AGENTS_DIR / f"{claude_agent_name(src.name)}.md"
        lines.append(_write_text(dest, translate_agent(src), dry_run))
    return lines


def port_commands(dry_run: bool = False) -> list[str]:
    """Translate ``.github/prompts/**/*.prompt.md`` and add starter commands.

    Nesting is preserved: Claude Code turns ``python/add-types.md`` into the
    namespaced ``/python:add-types`` command. Prompt-derived commands take
    precedence; a starter command is only written when no command of that name
    exists (on disk or from a ported prompt).
    """
    root = repo_root()
    lines: list[str] = []
    produced: set[str] = set()

    src_dir = root / COPILOT_PROMPTS_DIR
    if src_dir.is_dir():
        for src in sorted(src_dir.glob("**/*.prompt.md")):
            rel = src.relative_to(src_dir)
            dest = (
                root
                / CLAUDE_COMMANDS_DIR
                / rel.with_name(rel.name.removesuffix(".prompt.md") + ".md")
            )
            produced.add(dest.name)
            lines.append(_write_text(dest, translate_prompt(src), dry_run))

    for filename, (command, body) in _STARTER_COMMANDS.items():
        dest = root / CLAUDE_COMMANDS_DIR / filename
        if filename in produced or dest.exists():
            continue
        lines.append(_write_text(dest, command.render(body), dry_run))
    return lines


def port_skills(dry_run: bool = False) -> list[str]:
    """Mirror ``.github/skills/`` into ``.claude/skills/`` (identical SKILL.md).

    Skills present only under Claude (stale copies of removed Copilot skills)
    are pruned so the two stay in sync.
    """
    root = repo_root()
    src_dir = root / COPILOT_SKILLS_DIR
    dst_dir = root / CLAUDE_SKILLS_DIR
    sources = (
        {p.parent.name for p in src_dir.glob("*/SKILL.md")}
        if src_dir.is_dir()
        else set()
    )
    existing = {p.name for p in dst_dir.iterdir()} if dst_dir.is_dir() else set()

    lines: list[str] = []
    for name in sorted(sources):
        dest = dst_dir / name
        rel = dest.relative_to(root)
        if dry_run:
            lines.append(f"  [dry-run] {rel}")
            continue
        if dest.exists():
            shutil.rmtree(dest)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(src_dir / name, dest, ignore=shutil.ignore_patterns(".git"))
        lines.append(f"  mirrored {rel}")

    for stale in sorted(existing - sources):
        dest = dst_dir / stale
        if dry_run:
            lines.append(f"  [dry-run] prune {dest.relative_to(root)}")
            continue
        shutil.rmtree(dest)
        lines.append(f"  pruned {dest.relative_to(root)}")
    return lines


def port_all(dry_run: bool = False) -> list[tuple[str, list[str]]]:
    """Port every part of the Copilot setup into Claude Code files.

    Returns ``(section_title, status_lines)`` pairs for display.
    """
    return [
        ("Instructions", [port_instructions(dry_run)]),
        ("MCP", [port_mcp()]),
        ("Agents", port_agents(dry_run)),
        ("Commands", port_commands(dry_run)),
        ("Skills", port_skills(dry_run)),
    ]
