"""Ownership-safe writes for generated tool files.

Tara complements a repo; it never silently overwrites what the developer wrote.
Every write here first proves Tara produced what it is about to replace:

- Markdown files carry :data:`MARKER` on their first body line.
- Mirrored skill directories are recorded per tool in ``.tara/generated.json``.

Anything Tara cannot prove it owns is left alone. In an interactive session the
developer is asked whether to take it over; otherwise it is skipped and
reported, so a CI run can never destroy local work.
"""

from __future__ import annotations

import json
import shutil
import sys
from collections.abc import Iterable
from difflib import unified_diff
from pathlib import Path

import questionary

from tara.core import repo_root

MARKER = "<!-- generated by `tara integrations` -->"
_LEGACY_MARKER = "<!-- generated by `tara tools` -->"

STATE = Path(".tara") / "generated.json"


def marked(body: str) -> str:
    """Prefix a rendered body with the generated marker."""
    return f"{MARKER}\n\n{body.strip()}\n"


def is_generated(path: Path) -> bool:
    """Whether ``path`` is absent or is a regular file marked as Tara-generated."""
    if not path.exists():
        return True
    if not path.is_file() or path.is_symlink():
        return False
    try:
        body = path.read_text(encoding="utf-8")
        if any(marker in body for marker in (MARKER, _LEGACY_MARKER)):
            return True
    except (OSError, UnicodeDecodeError):
        return False
    return False


def _interactive() -> bool:
    return sys.stdin.isatty() and sys.stdout.isatty()


def _text_diff(rel: Path, current: str, replacement: str) -> str:
    """Render a unified diff between existing and proposed text."""
    return "".join(
        unified_diff(
            current.splitlines(keepends=True),
            replacement.splitlines(keepends=True),
            fromfile=f"{rel} (current)",
            tofile=f"{rel} (generated)",
        )
    )


def _tree_text(directory: Path) -> str:
    """Render a directory's readable files into stable text for a preview."""
    sections: list[str] = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.is_symlink():
            continue
        rel = path.relative_to(directory)
        try:
            body = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            body = "[binary or unreadable file]\n"
        sections.append(f"### {rel}\n{body}")
    return "\n".join(sections)


def confirm_takeover(dest: Path, replacement: str | Path, kind: str = "file") -> bool:
    """Show the proposed diff and ask before replacing an existing path."""
    if not _interactive():
        return False
    rel = dest.relative_to(repo_root())
    if isinstance(replacement, Path):
        if dest.is_dir() and not dest.is_symlink():
            current = _tree_text(dest)
        else:
            try:
                current = dest.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                current = "[binary or unreadable file]\n"
        proposed = _tree_text(replacement)
    else:
        try:
            current = dest.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            questionary.print(f"Cannot preview changes to {rel}; leaving it untouched.")
            return False
        proposed = replacement
    questionary.print(_text_diff(rel, current, proposed))
    return bool(
        questionary.confirm(
            f"{rel} was not generated by Tara. Overwrite this {kind}?",
            default=False,
        ).unsafe_ask()
    )


def write_generated(dest: Path, text: str, dry_run: bool, force: bool = False) -> str:
    """Write generated text, requiring confirmation before replacing user content.

    ``text`` must already carry :data:`MARKER` (see :func:`marked`), so a later
    run can recognise its own output.
    """
    root = repo_root()
    rel = dest.relative_to(root)
    if dest.is_symlink():
        return f"  skipped {rel} (destination is a symlink, left untouched)"
    if dest.is_file():
        try:
            if dest.read_text(encoding="utf-8") == text:
                return f"  unchanged {rel}"
        except (OSError, UnicodeDecodeError):
            pass
    if dest.exists() and not is_generated(dest) and not force:
        if not _interactive():
            return f"  skipped {rel} (overwrite requires --force)"
        if not confirm_takeover(dest, text):
            return f"  skipped {rel} (left untouched)"
    if dry_run:
        return f"  [dry-run] {rel}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    return f"  wrote {rel}"


# ── generated-state manifest ──────────────────────────────────────────────────


def _state_path() -> Path:
    return repo_root() / STATE


def read_state() -> dict[str, dict[str, list[str]]]:
    """Read ``.tara/generated.json``, or an empty mapping when it is absent."""
    path = _state_path()
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def owned(tool: str, kind: str) -> set[str]:
    """Names of ``kind`` artefacts Tara generated for ``tool`` on its last run."""
    return set(read_state().get(tool, {}).get(kind, []))


def record(tool: str, kind: str, names: Iterable[str]) -> None:
    """Record the ``kind`` artefacts Tara now owns for ``tool``."""
    state = read_state()
    state.setdefault(tool, {})[kind] = sorted(names)
    path = _state_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")


# ── skill mirroring ───────────────────────────────────────────────────────────


def mirror_skills(
    tool: str,
    src_dir: Path,
    dst_dir: Path,
    dry_run: bool,
    force: bool = False,
) -> list[str]:
    """Mirror ``src_dir``'s skills into ``dst_dir``, touching only what Tara owns.

    A destination directory Tara did not create is never replaced or pruned;
    only skills recorded in ``.tara/generated.json`` for ``tool`` are refreshed,
    and only those that have since disappeared from the source are removed.
    """
    root = repo_root()
    sources = (
        {p.parent.name for p in src_dir.glob("*/SKILL.md")}
        if src_dir.is_dir()
        else set()
    )
    previously = owned(tool, "skills")
    # Only real directories count; a stray file or symlink is the developer's.
    entries = {p.name: p for p in dst_dir.iterdir()} if dst_dir.is_dir() else {}
    existing = set(entries)
    existing_dirs = {
        name
        for name, path in entries.items()
        if path.is_dir() and not path.is_symlink()
    }
    lines: list[str] = []
    mirrored: set[str] = set()
    for name in sorted(sources):
        dest = dst_dir / name
        rel = dest.relative_to(root)
        # Present but not ours: it predates Tara or the developer wrote it.
        unowned = name in existing and (
            name not in previously or name not in existing_dirs
        )
        if dest.is_symlink():
            lines.append(f"  skipped {rel} (destination is a symlink, left untouched)")
            continue
        if unowned and not force:
            if not _interactive():
                lines.append(f"  skipped {rel} (overwrite requires --force)")
                continue
            if not confirm_takeover(dest, src_dir / name, "skill"):
                lines.append(f"  skipped {rel} (left untouched)")
                continue
        if dry_run:
            lines.append(f"  [dry-run] {rel}")
            mirrored.add(name)
            continue
        if dest.exists():
            if dest.is_dir():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(src_dir / name, dest, ignore=shutil.ignore_patterns(".git"))
        lines.append(f"  mirrored {rel}")
        mirrored.add(name)

    # Prune only skills Tara generated that the source no longer provides.
    for stale in sorted((previously & existing_dirs) - sources):
        dest = dst_dir / stale
        rel = dest.relative_to(root)
        if dry_run:
            lines.append(f"  [dry-run] prune {rel}")
            continue
        shutil.rmtree(dest)
        lines.append(f"  pruned {rel}")

    if not dry_run:
        record(tool, "skills", mirrored)
    return lines


def remove_generated_file(path: Path, dry_run: bool) -> str | None:
    """Remove one Tara-generated file while preserving unowned paths."""
    if not path.exists() or path.is_symlink() or not is_generated(path):
        return None
    rel = path.relative_to(repo_root())
    if dry_run:
        return f"  [dry-run] remove {rel}"
    path.unlink()
    return f"  removed {rel}"


def remove_generated_markdown(directory: Path, dry_run: bool) -> list[str]:
    """Remove marked Markdown files below a generated integration directory."""
    if not directory.is_dir() or directory.is_symlink():
        return []
    lines = [
        line
        for path in sorted(directory.rglob("*.md"))
        if (line := remove_generated_file(path, dry_run)) is not None
    ]
    if not dry_run:
        for path in sorted(directory.rglob("*"), reverse=True):
            if path.is_dir() and not path.is_symlink() and not any(path.iterdir()):
                path.rmdir()
        if directory.exists() and not any(directory.iterdir()):
            directory.rmdir()
    return lines


def remove_owned_skills(tool: str, directory: Path, dry_run: bool) -> list[str]:
    """Remove only skill directories recorded as generated by Tara."""
    lines: list[str] = []
    for name in sorted(owned(tool, "skills")):
        path = directory / name
        if not path.is_dir() or path.is_symlink():
            continue
        rel = path.relative_to(repo_root())
        if dry_run:
            lines.append(f"  [dry-run] remove {rel}")
            continue
        shutil.rmtree(path)
        lines.append(f"  removed {rel}")
    if not dry_run:
        record(tool, "skills", [])
        if directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()
    return lines
