"""Generate docs/cli.md from Tara's Typer app.

Run `uv run python scripts/gen_cli_docs.py` after changing the CLI. A test
(`tests/test_cli_docs.py`) regenerates the same content and fails if the
committed file is out of sync.
"""

from __future__ import annotations

from pathlib import Path

import typer
from typer.cli import get_docs_for_click
from typer.main import get_command

from tara.cli import app

HEADER = (
    "<!-- Generated by scripts/gen_cli_docs.py. Do not edit by hand. -->\n"
    "<!-- Run `uv run python scripts/gen_cli_docs.py` to refresh. -->\n\n"
)


def render() -> str:
    """Return the full CLI reference as Markdown."""
    cmd = get_command(app)
    ctx = typer.Context(cmd, info_name="tara")
    body = get_docs_for_click(obj=cmd, ctx=ctx, name="tara")
    # Exactly one trailing newline so the output agrees with the
    # end-of-file-fixer pre-commit hook (avoids a generate/lint tug-of-war).
    return HEADER + body.rstrip() + "\n"


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "docs" / "cli.md"
    out.write_text(render())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
